### ISSUE TITLE
SamsungTVPlus EPG request

### ISSUE THREAD

**Issue by Muradisher** [matthuisman/i.mjh.nz#150]
Hi.
Please can you add br.xml.gz to the epg Index of /SamsungTVPlus/ and then add Brazilian EPGs especially for this channel that I'm looking for called Revry Brazil. 

Apparently there are now Brazilian channels on SamsungTVPlus. 
But your uploaded epg index does not have the br.xml.gz (Brazil). 
So I cannot find anywhere the epg for Revry Brazil. 

https://i.mjh.nz/SamsungTVPlus/
![Screenshot_2024-12-28-15-23-47](https://github.com/user-attachments/assets/752eabc2-0ef8-4f06-be91-b05a42517691)

The link for the TV guide source is https://watch.revry.tv/live%20tv

The link for the channel is 
https://www.apsattv.com/ssungbra.m3u

**Comment by matthuisman** [comment]
Hi, not possible sorry due to the below:

"The data generator uses the Samsung TV Plus [Android App](https://play.google.com/store/apps/details?id=com.samsung.android.tvplus) API to fetch the channels.
Therefore only regions / channels available on that app are currently available.
https://www.apsattv.com/streams.html has some manually created playlists for other regions."
