### ISSUE TITLE
7mate Sydney not playing

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/i.mjh.nz#56]

**Comment by Matrix40au** [comment]
I have Kodi Matrix 19 5 installed, with Slyguy Plugin (updated to latest version)

Simple PVR, and IPTV merge, and IPTV_AU. I get the EPG up and running. I get every channel, but weird thing is that 7mate failed to load, I get the preview image and then when I try to play, it goes black then back to the TV guide, no crash warnings.

I suspect 7mate has changed IDs because they now you 7mateHD, but I assumed you fixed that error and now a new one has popped up.

Thanks Matt for understanding, I hope this is just an isolated incidence. I'm missing my 7mate shows real bad.
(Partner doesn't watch TV, so I stream on my mobile to catch up on ABC news and 7mate, 9Life, where I can)

**Comment by matthuisman** [comment]
fixed now. They have reduced quality for non-drm streams.
You can use the 7play kodi addon if you want 720p streams that use Widevine

**Comment by Matrix40au** [comment]
> fixed now. They have reduced quality for non-drm streams. You can use the 7play kodi addon if you want 720p streams that use Widevine

Yeah all fixed up now, much appreciated!
